name: msnger
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.3
  flutter_riverpod: ^1.0.3
  freezed_annotation: ^2.0.3
  go_router: ^3.1.0
  grpc: ^3.0.2
  hooks_riverpod: ^1.0.3
  objectbox: ^1.5.0
  objectbox_flutter_libs: ^1.5.0
  nt4f04unds_widgets:
    # path: c:/dev/projects/native/nt4f04unds_widgets/
    git:
      url: https://github.com/nt4f04uNd/nt4f04unds_widgets/
      ref: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: 2.0.3+1
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  objectbox_generator: ^1.5.0

flutter:
  uses-material-design: true
